ワークフローの修正。

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -1,14 +1,16 @@
-# Sample workflow for building and deploying a Next.js site to GitHub Pages
-#
-# To get started with Next.js see: https://nextjs.org/docs/getting-started
-#
-name: Build and Deploy Next.js site to GitHub Pages
+name: Deploy Lambda
 
 on:
-  workflow_run:
-    workflows: ["Deploy Lambda"]
-    types:
-      - completed
+  # Runs on pushes targeting the default branch
+  push:
+    branches: ["main"]
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
+
+env:
+  project_name: learning-network-v4
+  app_dir: ./api/my-app
+  api_dir: ./api
 
 # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
 permissions:
@@ -22,7 +24,67 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  test:
+  lambda-test:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v2
+        with:
+          node-version: '18.x'
+      - run: npm install
+        working-directory: ${{ env.app_dir }}
+      - run: npm run test
+        working-directory: ${{ env.app_dir }}
+    outputs:
+      test-status: ${{ job.status }}
+  lambda-deploy:
+    needs: lambda-test
+    if: ${{ needs.lambda-test.outputs.test-status == 'success' }}
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-python@v3
+      - uses: aws-actions/setup-sam@v2
+      - uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+      - run: sam build --use-container
+        working-directory: ${{ env.api_dir }}
+      - name: Deploy Lambda
+        run: |
+          sam deploy \
+            --no-confirm-changeset \
+            --no-fail-on-empty-changeset \
+            --resolve-image-repos \
+            --stack-name ${{ env.project_name }} \
+            --s3-bucket ${{ env.project_name }} \
+            --capabilities CAPABILITY_IAM \
+          || aws s3 mb s3://${{ env.project_name }} && sam deploy \
+            --no-confirm-changeset \
+            --no-fail-on-empty-changeset \
+            --resolve-image-repos \
+            --stack-name ${{ env.project_name }} \
+            --s3-bucket ${{ env.project_name }} \
+            --capabilities CAPABILITY_IAM
+        working-directory: ${{ env.api_dir }}
+      - name: Get API Gateway URL
+        run: |
+          API_GATEWAY_URL=$(aws cloudformation describe-stacks --stack-name ${{ env.project_name }} --query "Stacks[0].Outputs[?OutputKey=='YourInfoApi'].OutputValue" --output text --no-cli-pager)
+          echo "API_GATEWAY_URL=$API_GATEWAY_URL" >> $GITHUB_ENV
+      - name: Cat API Gateway URL
+        run: echo $API_GATEWAY_URL
+      - name: Check status code of curl response
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" "${{ env.API_GATEWAY_URL }}")
+          if [ $response -eq 200 ]; then
+            echo "Success"
+          else
+            echo "Failed"
+            exit 1
+          fi
+  nextjs-test:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -56,9 +118,9 @@ jobs:
     outputs:
       test-status: ${{ job.status }}
   # Build job
-  build:
-    needs: test
-    if: ${{ needs.test.outputs.test-status == 'success' }}
+  nextjs-build:
+    needs: nextjs-test
+    if: ${{ needs.nextjs-test.outputs.test-status == 'success' }}
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -126,14 +188,13 @@ jobs:
         uses: actions/upload-pages-artifact@v1
         with:
           path: ./dist
-
   # Deployment job
-  deploy:
+  nextjs-deploy:
     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
     runs-on: ubuntu-latest
-    needs: build
+    needs: nextjs-build
     steps:
       - name: Deploy to GitHub Pages
         id: deployment
