小さな修正。

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -141,7 +141,18 @@ jobs:
       #     echo "${{ secrets.ENV_LOCAL }}" > .env.local
       - name: Show API Gateway URL
         run: |
-          cat ${{ env.API_GATEWAY_URL }}
+          echo ${{ env.API_GATEWAY_URL }}
+      - name: Check status code of curl response
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" "${{ env.API_GATEWAY_URL }}/your-info")
+          if [ $response -eq 200 ]; then
+            echo "Success"
+          else
+            echo "Failed"
+            echo "Response code: $response"
+            echo "API Gateway URL: ${{ env.API_GATEWAY_URL }}"
+            exit 1
+          fi
       - name: Set API Gateway URL
         run: |
           echo "NEXT_PUBLIC_LAMBDA_API_URL=${{ env.API_GATEWAY_URL }}$\n" >> .env.local
